# Generated by Django 4.0.4 on 2022-05-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenmates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='moim',
        ),
        migrations.AddField(
            model_name='userreview',
            name='mate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='greenmates.mate'),
            preserve_default=False,
        ),
    ]
